# config/routes/attributes.yaml
controllers:
    resource:
        path: ../../src/Controller/
        namespace: Bits\Themply\Controller
    type: attribute

kernel:
    resource: Bits\Themply\Kernel
    type: attribute