page_lucky:
    path: /lucky
    # the controller value has the format 'controller_class::method_name'
    controller: Bits\Themply\Controller\LuckyController::number
    type: annotation
    
themply:
    path: /contao?do=themply
    controller: Bits\Themply\ThemplyModule::run
    type: annotation