bits.themply.controller:
    resource: ../src/Controller
    type: attribute
    
    Bits\Themply\Controller\LuckyController:
        path: /contao/themply
        controller: Bits\Themply\Controller\LuckyController::__invoke
        type: annotation
    
     bits.themply.controller.luckycontroller:
        path: /contao/themply
        controller: Bits\Themply\Controller\LuckyController::__invoke
        type: annotation

