    Bits\Themply\Controller\BackendController:
        path: /contao/themply
        controller: Bits\Themply\Controller\BackendController::__invoke
        type: annotation
    
    bits.themply.controller.backendcontroller:
        path: /contao/themply
        controller: Bits\Themply\Controller\BackendController::__invoke
        type: annotation

