<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'page_lucky' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky']], [], [], []],
    'App\Controller\LuckyController::number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky']], [], [], []],
];
